; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
; Set the default environment to build if none is specified
default_envs = esp32-base

[env]
; Shared settings for all environments
framework = arduino
monitor_speed = 115200
; Optional: add shared libraries here if needed
; lib_deps = 

# Base configuration for ESP32 - Inherited by demo envs
[env:esp32-base]
platform = espressif32
board = esp32doit-devkit-v1

; Base configuration for ESP8266
[env:esp12e]
platform = espressif8266
board = esp12e

; Demo for Wind Speed (extends the ESP32 base)
[env:demo_wind_speed]
extends = env:esp32-base
; +<*> -<*> resets the filter; then includes the specific test folder
build_src_filter = +<*> -<*> -<main.cpp> +<../test/demo_wind_speed/>

# Demo for Wind Direction - Extends the ESP32 base
[env:demo_wind_direction]
extends = env:esp32-base
; +<*> -<*> resets the filter; then includes the specific test folder
build_src_filter = +<*> -<*> -<main.cpp> +<../test/demo_wind_direction/>
